# Generated by Django 4.0.6 on 2022-07-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0002_detailsproduct_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterField(
            model_name='products',
            name='keyword',
            field=models.CharField(blank=True, db_index=True, max_length=400, null=True, verbose_name='کلمه کلیدی'),
        ),
        migrations.AlterField(
            model_name='products',
            name='property',
            field=models.ManyToManyField(blank=True, null=True, to='product_module.productproperty', verbose_name='ویژگی ها'),
        ),
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(db_index=True, max_length=300, verbose_name='نام محصول'),
        ),
    ]
