# Generated by Django 4.0.6 on 2022-08-06 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0005_productcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcomment',
            name='response',
        ),
        migrations.AddField(
            model_name='productcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.productcomment', verbose_name='والد'),
        ),
    ]
