# Generated by Django 4.0.6 on 2022-10-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0006_remove_productcomment_response_productcomment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discount_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='تخفیف'),
        ),
    ]
