# Generated by Django 4.0.6 on 2022-10-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0007_products_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_discount',
            field=models.BooleanField(blank=True, null=True, verbose_name='تخفیف فعال'),
        ),
    ]
