# Generated by Django 4.0.6 on 2022-11-27 19:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0008_products_is_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, db_index=True, null=True, verbose_name='توضیحات اصلی'),
        ),
    ]
