# Generated by Django 4.0.6 on 2022-08-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardImageSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='نام استاندارد')),
                ('image', models.ImageField(upload_to='images/standard', verbose_name='تصویر استاندارد')),
            ],
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/site-setting/', verbose_name='تصویر تاییدیه سایت'),
        ),
    ]
