# Generated by Django 4.0.6 on 2022-09-01 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0004_agentmodel_alter_standardimagesite_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutusmodel',
            name='services',
        ),
        migrations.AddField(
            model_name='agentmodel',
            name='services',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_module.aboutusmodel', verbose_name='نماینده ها'),
        ),
        migrations.AlterField(
            model_name='aboutusmodel',
            name='body_text',
            field=models.TextField(blank=True, null=True, verbose_name='متن اصلی صفحه درباره ما'),
        ),
        migrations.AlterField(
            model_name='aboutusmodel',
            name='text_service',
            field=models.TextField(blank=True, null=True, verbose_name='متن اصلی صفحه خدمات پس از فروش'),
        ),
    ]
