# Generated by Django 4.0.6 on 2022-09-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0005_remove_aboutusmodel_services_agentmodel_services_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentmodel',
            name='services',
        ),
        migrations.AddField(
            model_name='aboutusmodel',
            name='services',
            field=models.ManyToManyField(blank=True, null=True, to='site_module.agentmodel', verbose_name='نماینده ها'),
        ),
    ]
