# Generated by Django 4.0.6 on 2022-09-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0006_remove_agentmodel_services_aboutusmodel_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_category', models.ImageField(upload_to='images/sliders', verbose_name='تصویر دسته بندی خانه')),
                ('image_bottom', models.ImageField(upload_to='images/sliders', verbose_name='تصویر پایین صفحه خانه')),
            ],
            options={
                'verbose_name': 'تنظیمات خانه ',
                'verbose_name_plural': 'تنظیمات صفحه خانه',
            },
        ),
        migrations.AlterModelOptions(
            name='aboutusmodel',
            options={'verbose_name': 'تنظیمات درباره ما ', 'verbose_name_plural': 'تنظیمات صفحه درباره ما'},
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/site-setting/', verbose_name='تصویر Enamad'),
        ),
    ]
