# Generated by Django 4.0.6 on 2022-09-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0007_homemodel_alter_aboutusmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homemodel',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='فعال/غیرفعال'),
            preserve_default=False,
        ),
    ]
