# Generated by Django 4.0.6 on 2022-09-16 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0002_newsletters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validity_date', models.CharField(blank=True, max_length=250, null=True, verbose_name='مدت اعتبار گارانتی')),
                ('code_validity', models.CharField(max_length=200, verbose_name='کد گارانتی')),
                ('product_name', models.CharField(max_length=350, verbose_name='اسم محصول')),
                ('detail', models.CharField(max_length=400, verbose_name='اطلاعات بیشتر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
