# Generated by Django 4.0.6 on 2022-09-16 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0003_warranty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warranty',
            options={'verbose_name': 'گارانتی', 'verbose_name_plural': 'کد های گارانتی'},
        ),
    ]
