# Generated by Django 4.0.6 on 2022-09-23 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0004_alter_warranty_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warranty',
            name='detail',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='اطلاعات بیشتر'),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
