# Generated by Django 4.0.6 on 2022-09-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0006_alter_warranty_code_validity_discountcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='diccount_price',
            field=models.CharField(default=1000, max_length=500, verbose_name='قیمت کد تخفیف'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='code_discount',
            field=models.CharField(max_length=200, unique=True, verbose_name='کد تخفیف'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='validity_date',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='مدت اعتبار تخفیف'),
        ),
    ]
